{% set name = "hoggorm" %}
{% set version = "0.13.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hoggorm-{{ version }}.tar.gz
  sha256: f1254d860f3024b2e6a2cecb2c0152f2010596235058781856c3a1a2f075c3b6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - sphinx
    - numpy >=1.9 # the package itself imports numpy when running setup.py

  run:
    - numpy >=1.9
    - python >={{ python_min }}

test:
  imports:
    - hoggorm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/olivertomic/hoggorm
  summary: Package for explorative multivariate statistics
  license: BSD-2-Clause
  license_file: LICENSE
  description: |
    hoggorm is a Python package for explorative multivariate 
    statistics Including PCA, PCR, PLSR, PLSR1, PLSR2, matrix 
    correlation coefficients RV, RV2 and SMI. hoggorm aims at 
    understanding and interpretation of the variance in the data.
  doc_url: https://hoggorm.readthedocs.io
  dev_url: https://github.com/olivertomic/hoggorm

extra:
  recipe-maintainers:
    - andife
